workdonereport/urls.py
from django.contrib import admin
from django.urls import path
from workreport import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.welcomeMsg),
    path('home/',views.home,name='home'),
    path('getinfo/<int:pk>',views.getinfo,name='getinfo'),
    path('addDetails/<int:pk>',views.addDetails,name='addDetails'),
    path('signUp/',views.signUp,name='signUp'),
    path('signin/',auth_views.LoginView.as_view(template_name='workreport/login.html'),name='login'),
    path('signout/',auth_views.LogoutView.as_view(template_name='workreport/logout.html'),name='logout'),
    path('profile/<int:pk>',views.profile,name='profile'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

workreport/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Details(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
	programName = models.CharField(max_length=100)
	collegeName = models.CharField(max_length=100)
	districName = models.CharField(max_length=100)
	startDate = models.DateField()
	endDate = models.DateField()
	refernceLink = models.CharField(max_length=200) 
	
	def __str__(self):
		return self.programName+' '+self.collegeName
	
class Profile(models.Model):
	vals = [('Male','Male'),('FeMale','FeMale')]
	age = models.IntegerField(null=True)
	phoneNo = models.CharField(max_length=10)
	gender = models.CharField(max_length=10,choices=vals)
	picture = models.ImageField(upload_to='profilepics/',null=True)
	date_of_birth = models.DateField(null=True)
	user = models.OneToOneField(User,on_delete=models.CASCADE)


	def __str__(self):
		return self.phoneNo

workreport/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from workreport.models import Details,Profile
from django import forms
# from functools import partial
# DateInput = partial(forms.DateInput, {'class': 'datepicker'})
class DetailsForm(ModelForm):
	class Meta:
		model = Details
		fields = ['programName','collegeName','districName','startDate','endDate','refernceLink']


class DetailsFormWd(forms.Form):
	programName = forms.CharField(label = "Program Name",
		widget=forms.TextInput(attrs={"class":'form-control','placeholder':"Enter program Name"}))
	collegeName = forms.CharField(label = "College Name",
		widget=forms.TextInput(attrs={"class":'form-control','placeholder':"Enter College Name"}))
	districName = forms.CharField(label = "District Name",
		widget=forms.TextInput(attrs={"class":'form-control','placeholder':"Enter DistrictName"}))
	startDate = forms.DateField(label = 'Start Date',
		widget = forms.DateInput(attrs={'class':'form-control datepicker','placeholder':'Select Start Date'}))
	endDate = forms.DateField(label = 'End Date',
		widget = forms.DateInput(attrs={'class':'form-control datepicker','placeholder':'Select End Date'}))
	refernceLink = forms.CharField(label = "Reference Name",
		widget=forms.TextInput(attrs={"class":'form-control','placeholder':"Enter Reference Name"}))



class UsersignupForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['first_name','last_name','username','email','password1','password2']


class ProfileForm(ModelForm):
	class Meta:
		model = Profile
		fields = ['age','phoneNo','gender','picture','date_of_birth']

workreport/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User

from workreport.models import Details,Profile
from workreport.forms import DetailsFormWd,DetailsForm,UsersignupForm,ProfileForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

def welcomeMsg(request):
	return HttpResponse('Hi,Welcome to My Page')

def home(request):
	return render(request,'workreport/home.html',{})

def signUp(request):
	if request.method=='POST':
		form = UsersignupForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('login')
	form  = UsersignupForm()
	return render(request,'workreport/signUp.html',{'form':form})

@login_required
def getinfo(request,pk):
	data = Details.objects.filter(user_id=pk)
	return render(request,'workreport/details.html',{'data':data})
@login_required
def addDetails(request,pk):
	data = User.objects.get(id=pk)
	form  = DetailsForm()
	if request.method == 'POST':
		formdata = DetailsForm(request.POST)
		print('ok')
		if formdata.is_valid():
			print('i am here')
			f=formdata.save(commit=False)
			f.user_id = data.id
			f.save()
			messages.success(request, 'Details Addedd Successfully...')
			return render(request,'workreport/addDetails.html',{'form':form})
		return HttpResponse('Something is wrong..')
	
	return render(request,'workreport/addDetails.html',{'form':form})


@login_required
def profile(request,pk):
	data = User.objects.get(id=pk)
	if request.method=='POST':
		info = Profile.objects.filter(user_id = pk).first()
		if info:
			form = ProfileForm(request.POST,request.FILES,instance=info)
			if form.is_valid():
				form.save()
				return redirect('home')
			print('i am')
		else:
			form = ProfileForm(request.POST,request.FILES)
			if form.is_valid():
				print('i am here'+ str(pk)	 +' '+ request.POST['phoneNo'])
				try:
					f=form.save(commit=False)
					f.user_id = data.id
					f.save()
					return redirect("home")
				except:
					return HttpResponse("<script>window.alert('something wrong')</script>")
	else:
		info = Profile.objects.filter(user_id = pk).first()
		if(info):
			print('i came to here')
			form = ProfileForm(instance=info)
			return render(request,'workreport/profile.html',{'form':form,'data':data}) 
		else:
			form = ProfileForm()
			return render(request,'workreport/profile.html',{'form':form,'data':data}) 

workreport/templates/workreport/addDetails.html
{% extends 'workreport/header.html' %}
{% block title %}SignIn Form {%endblock title%}
{% block content %}
<div class="container">
	
	<div class="jumbotron col-md-6" style="margin: auto;margin-top: 30px;">
		{% for message in messages %}
	<div class="alert alert-{{ message.tags }} alert-dismissible">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		{% if messages %}
	<h4 class="messages">
	    
	    {{ message }}
	    
	</h4>
	{% endif %}
	</div>
	{% endfor %}
		<form action="" method="POST">
			{% csrf_token %}
			{{form.as_p}}
		<button type="submit" class="btn btn-primary">Add</button>
		</form>
	</div>
</div>
{%endblock content %}

workreport/templates/workreport/details.html
{% extends 'workreport/header.html' %}
{% block title %}SignIn Form {%endblock title%}
{% block content %}
<div class="container">
	<h3 style="text-align: center">Work Details</h3>
	<table class="table">
		<thead class="thead-dark">
			<tr>
				<th>ProgramName</th>
				<th>CollegeName</th>
				<th>DistricName</th>
				<th>StartDate</th>
				<th>EndDate</th>
				<th>RefernceLink</th>

			</tr>
		</thead>
		<tbody>
			{% for info in data%}
			<tr>
				<td>{{info.programName}}</td>
				<td>{{info.collegeName}}</td>
				<td>{{info.districName}}</td>
				<td>{{info.startDate}}</td>
				<td>{{info.endDate}}</td>
				<td>{{info.refernceLink}}</td>
			</tr>
			{%endfor%}
		</tbody>
	</table>
</div>
{%endblock content %}

workreport/templates/workreport/header.html
{% load static %}
<html>
<head>
	<title>{% block title %}MyPage{% endblock title %}</title>
	<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" type="text/css" href="{% static 'CSS/bootstrap.min.css'%}">
	<script src="{% static 'JS/jquery.min.js'%}"></script>
	  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script type="text/javascript" src="{% static 'JS/bootstrap.min.js' %}"></script>
	<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
  	<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
  	  <script>

	$(document).ready(function() {
	    $('#id_startDate').datepicker({
	    	format: 'yyyy-mm-dd'
	    });
	    $('#id_endDate').datepicker({
	    	format: 'yyyy-mm-dd'
	    });
	});
</script>
</head>
<body>
	{% include 'workreport/navbar.html' %}
	{% block content %}
		
	{% endblock content %}

</body>
</html>

workreport/templates/workreport/home.html
{% extends 'workreport/header.html' %}
{% block title %}
Home Page
{%endblock title%}
	
{% block content %}
<div class="container">
		<div class="card card-body" style="margin: auto;margin-top: 30px;">
			Project status reports are timely updates (we’ll discuss how often you should be doing them later) on the progress of your projects. They answer the questions everyone seems to be asking (before they actually ask them). Written concisely, they offer high-level information about a project, rather than every detail.
<br><br>
Doing project status reports regularly is important because they help you keep all stakeholders in the loop and aligned on how your project is progressing. You’ll get considerably fewer questions about project status because you’re already ahead of the game. They show (and tell) that you’re on track, making you (and everyone else) feel confident.
<br>
<br>
And if your project isn’t on track, your status report will let others know what the delay is and what you’re doing to resolve any blockers, allowing you to show off your proactive approach to getting things back to where they should be. (A project timeline is another excellent addition to managing your projects).
		</div>
	</div>
{%endblock content %}

workreport/templates/workreport/login.html
{% extends 'workreport/header.html' %}
{% block title %}SignIn Form {%endblock title%}
{% block content %}
<div class="row justify-content-center" style="margin: auto;margin-top: 30px;">
	<div class="card">
		<div class="card-header bg-info">LogIn Form</div>
		<div class="card-body">
			<form method="POST" action="">
				{% csrf_token %}
				{{form.as_p}}
				<button class="btn btn-info" type="submit">signIn</button>
			</form>
		</div>
	</div>
</div>
{%endblock content %}

workreport/templates/workreport/logout.html
{% extends 'workreport/header.html' %}
{% block title %}SignOut Form {%endblock title%}
{% block content %}
<div class='col-md-6' style="margin: auto;margin-top: 30px;">
	<div class="alert alert-info">
		<div class="justify-content-center">
		<h2>you have been logged out </h2>
			<a href="{%url 'login'%}">click here to login again</a>
	</div>
</div>
</div>
{%endblock content %}

workreport/templates/workreport/navbar.html
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="#">Work Done Report</a>

  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav ml-auto">
      {% if not user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{%url 'signUp' %}">SignUp</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'login'%}">SignIn</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class='nav-link' href="{%url 'addDetails' user.id %}">AddReport</a>
      </li>
      <li class="nav-item">
        <a class='nav-link' href="{%url 'getinfo' user.id %}">GetDetails</a>
      </li>
      <li class="nav-item">
        <a class='nav-link' href="{%url 'profile' user.id %}">Profile</a>
      </li>
      <li class="nav-item">
        <a class='nav-link' href="#">Hi,Welcome {{request.user}}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'logout'%}">SignOut</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

workreport/templates/workreport/profile.html
{% extends 'workreport/header.html' %}
{% block title %}Update Form {%endblock title%}
{% block content %}

<div class="row justify-content-center" style="margin: auto;margin-top: 30px;">
	<div class="col-sm-5">
		<div class="card">
		<div class="card-header">
			{% if request.user.profile.picture %}
				<img src="/Images/{{request.user.profile.picture}}" height="70px" width="100px">
			{% endif %}
		Profile Form</div>
		<div class="card-body">
			<h1>{{request.user.details.age}}</h1>
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				
				{{ form.as_p}}
				<button class="btn btn-info" type="submit">update</button>
			</form>
		</div>
	</div>
	</div>
</div>
{%endblock content %}

workreport/templates/workreport/signUp.html
{% extends 'workreport/header.html' %}
{% block title %}SignOut Form {%endblock title%}
{% block content %}
<div class="row justify-content-center" style="margin: auto;margin-top: 30px;">
		<div class="col-sm-6 col-md-6">
			<div class="card">
	<form method="POST" action="">
		<div class="card-header bg-primary">Signup Form</div>
		<div class="card-body">
		{% csrf_token %}
		{{ form.as_p }}
		<button class ='btn btn-info'type="submit">SignUp</button>
		</div>
	</form>
	</div>
		</div>
	
</div>
{%endblock content %}